### ISSUE TITLE
sync plugin doesn't cancel jenkins job if openshift build is canceled

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#96] opened 2016-07-19 16:43 UTC
see: https://bugzilla.redhat.com/show_bug.cgi?id=1357752

**Comment by jimmidyson** [comment] 2016-07-22 09:29
Just to confirm what status should a job have when it's been cancelled. I was expecting `Running`, with `status.cancelled=true`. Is that not right? This is what I'm observing & cancelling from `oc cancel-build` is working fine for me.

**Comment by jimmidyson** [comment] 2016-07-22 09:37
Could you also share any Jenkins logs please?

**Comment by bparees** [comment] 2016-07-22 14:11
build.Status.Phase will be "Cancelled".

i haven't attempted to reproduce this myself, but you can ask QE for logs on the referenced bugzilla bug.  (QE doesn't look at issues, bugzilla is their process)

**Comment by jimmidyson** [comment] 2016-07-22 15:31
Looks like this has been confirmed as fixed in https://trello.com/c/ntM08mDF/868-8-pipeline-job-synchronizer#comment-5791eecd3aa58fb35923b878 - closing this now.

**Closed by jimmidyson** 2016-07-22 15:31 UTC

**Comment by xingxingxia** [comment] 2016-08-17 09:59
> i haven't attempted to reproduce this myself, but you can ask QE for logs on the referenced bugzilla bug. (QE doesn't look at issues, bugzilla is their process)
QE always check bugzilla, sometimes looks at issues/PRs too :) ^_^
Pasted jenkins logs in https://bugzilla.redhat.com/show_bug.cgi?id=1357752#c8 , pls take a look, thanks

**Comment by bparees** [comment] 2016-08-17 13:54
Seems like this should be re-opened based on the latest updates in the bugzilla bug. (i don't have the power to do so).  @iocanel can you take a look?  @jimmidyson says you're covering sync plugin while he's on PTO :)
