### ISSUE TITLE
Not possible to leave the namespace field in global config blank

### ISSUE THREAD

**Issue by siamaksade** [fabric8io/openshift-jenkins-sync-plugin#97] opened 2016-07-26 08:56 UTC
When leaving the namespace field in Global Configuration to blank in order to sync with all namespaces [1], the namespace resets to Jenkins namespace after saving. It should stay blank to include all namespaces.

[1] https://github.com/fabric8io/openshift-jenkins-sync-plugin/blob/master/src/main/resources/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration/config.jelly#L30

**Comment by bparees** [comment] 2016-07-26 12:51
@jimmidyson what would "all namespaces" even mean?  the plugin isn't going to have permission to retrieve the list of all namespaces, or sync against most of them.  I think this doc is just wrong.

**Comment by pat2man** [comment] 2016-10-26 23:02
@bparees it does seem like doc should be rewritten but I would find the ability to connect to multiple projects quite useful. Right now I have to create a separate Jenkins deployment for each project. Technically the plugin could have those permissions.

**Comment by bparees** [comment] 2016-10-26 23:05
@pat2man unfortunately i don't believe the openshift apis allow you to query for "all namespaces i can see" so the best we can do is allow you to list all the namespaces you want to sync explicitly, for which this issue exists: https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/63

**Comment by jimmidyson** [comment] 2016-11-03 13:27
We can query `/oapi/v1/projects` to get the list of projects that are accessible & I guess we could watch that list to update what is projects have BCs synced. This will need multiple watchers per namespace for this which will increase memory/CPU requirements but should be manageable.

So this should handle either blank project (renamed from namespace to be in sync with OpenShift parlance) which will watch all accessible projects, or accept a list of projects to watch.

Note that this will of course require the SA that Jenkins runs as to have correct karma to the target projects prior to starting the watches. It would be great to be able to populate an error when the config is validated if projects are not accessible, plus have to think about how to handle & notify if karma is revoked.

**Comment by jimmidyson** [comment] 2016-11-03 13:27
Now I've said that I'm going to close this as a dupe of #63 & continue to track this there.

**Closed by jimmidyson** 2016-11-03 13:27 UTC
Labels: priority/P2
