### ISSUE TITLE
status is not being synced by the poll loop

### ISSUE THREAD

**Issue by jwforres** [fabric8io/openshift-jenkins-sync-plugin#85] opened 2016-06-15 20:56 UTC
I see status getting synced after the job is complete and finalized, but it never syncs prior to that.  This means the openshift build is staying in "New" until the jenkins pipeline has either completed successfully or failed.

```
Jun 15, 2016 8:53:04 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onStarted
INFO: starting polling build job/sample-pipeline/10/
Jun 15, 2016 8:54:22 PM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: sample-pipeline #10 completed: SUCCESS
Jun 15, 2016 8:54:22 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: Patching build in namespace pipelineproject with name: sample-pipeline-8 phase: Complete
Jun 15, 2016 8:54:22 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onCompleted
INFO: onCompleted job/sample-pipeline/10/
Jun 15, 2016 8:54:22 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
INFO: Patching build in namespace pipelineproject with name: sample-pipeline-8 phase: Complete
Jun 15, 2016 8:54:22 PM io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onFinalized
INFO: onFinalized job/sample-pipeline/10/
```

**Comment by jwforres** [comment] 2016-06-15 20:58
@jimmidyson  @spadgett @ALRubinger

**Comment by jimmidyson** [comment] 2016-06-15 21:26
What version of the plugin is installed? 0.0.6 released earlier & images
updated today should be working fine. Can you confirm please?

**Comment by jwforres** [comment] 2016-06-15 21:44
It is version 0.0.6 of the sync plugin, verified from the Jenkins plugin
mgmt page.  I started with a fresh install this afternoon so it was today's
image.

**Comment by jimmidyson** [comment] 2016-06-15 21:47
Hmm OK will look that in the morning. The sync loop doesn't seem to have run at all.

**Comment by jimmidyson** [comment] 2016-06-17 09:34
Confirmed & closed.

**Comment by fabianofranz** [comment] 2016-07-08 22:58
@jimmidyson is this supposed to be fixed in 0.0.9? I'm seeing exactly this same issue with a brand new environment following origin/examples/jenkins/pipelines (OpenShift Sync is listed as 0.0.9 as the installed version). @jwforres

**Comment by jimmidyson** [comment] 2016-07-12 09:07
@fabianofranz What version of openshift are you running? Can you share the Jenkins logs please?

**Comment by fabianofranz** [comment] 2016-07-12 14:11
@jimmidyson It's Origin master. I saw the issue last friday but couldn't reproduce it by monday. Let me check if I still have the logs. I think @rhamilto is seeing it today.

**Comment by fabianofranz** [comment] 2016-07-14 18:58
@jimmidyson Ok, I was just able to reproduce this. 

I changed my Jenkinsfile (added a new stage) and it started to happen again - annotations are only being synced back to the build in OpenShift after the entire build ends. I tried and were able to reproduce it 3 times consecutively. Something about script approvals maybe? The Jenkins logs ("all") doesn't seem to have anything relevant:

```
Jul 14, 2016 6:49:09 PM INFO io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2 call
Updated job sample-pipeline from BuildConfig NamespaceName{pipelineproject:sample-pipeline} with revision: 338351
Jul 14, 2016 6:49:13 PM INFO io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onStarted
starting polling build job/sample-pipeline/29/
Jul 14, 2016 6:51:34 PM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
sample-pipeline #29 completed: SUCCESS
Jul 14, 2016 6:51:34 PM INFO io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
Patching build in namespace pipelineproject with name: sample-pipeline-29 phase: Complete
Jul 14, 2016 6:51:34 PM INFO io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onCompleted
onCompleted job/sample-pipeline/29/
Jul 14, 2016 6:51:34 PM INFO io.fabric8.jenkins.openshiftsync.BuildSyncRunListener upsertBuild
Patching build in namespace pipelineproject with name: sample-pipeline-29 phase: Complete
Jul 14, 2016 6:51:34 PM INFO io.fabric8.jenkins.openshiftsync.BuildSyncRunListener onFinalized
onFinalized job/sample-pipeline/29/
```

If I go ahead and deploy Jenkins again, it gets fixed.

@jwforres I'd say this should be reopened.

**Comment by jwforres** [comment] 2016-07-14 19:19
@jimmidyson can you reopen

**Comment by rhamilto** [comment] 2016-07-18 14:27
> If I go ahead and deploy Jenkins again, it gets fixed.

Thanks for posting this workaround, @fabianofranz.

**Comment by bparees** [comment] 2016-10-31 15:53
also tracked as https://bugzilla.redhat.com/show_bug.cgi?id=1390293

**Comment by jimmidyson** [comment] 2016-11-02 21:24
I may have just found a race between updating job configuration & triggering new jobs. I'll continue to try to reproduce consistently so I can prove any fix I come up with,

**Closed** 2016-11-03 13:37 UTC
Labels: priority/P1
