### ISSUE TITLE
Watcher closed exception

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#110] opened 2016-11-24 03:31 UTC
During our pipeline test the build request went unfulfilled and it looks like it was because the sync plugin's watcher got an exception and didn't recover:

```
INFO: Updated job extended-test-jenkins-pipeline-rnd6o-fbfct-sample-pipeline from BuildConfig NamespaceName{extended-test-jenkins-pipeline-rnd6o-fbfct:sample-pipeline} with revision: 3162
java.io.IOException: closed
	at okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:119)
	at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
	at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onClose(WatchConnectionManager.java:266)
	at okhttp3.internal.ws.RealWebSocket.peerClose(RealWebSocket.java:197)
	at okhttp3.internal.ws.RealWebSocket.access$200(RealWebSocket.java:38)
	at okhttp3.internal.ws.RealWebSocket$1$2.execute(RealWebSocket.java:84)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.io.IOException: closed
	at okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:119)
	at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
	at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onClose(WatchConnectionManager.java:266)
	at okhttp3.internal.ws.RealWebSocket.peerClose(RealWebSocket.java:197)
	at okhttp3.internal.ws.RealWebSocket.access$200(RealWebSocket.java:38)
	at okhttp3.internal.ws.RealWebSocket$1$2.execute(RealWebSocket.java:84)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
<----end of log for "jenkins-1-wljl2"
```

full log can be seen here (scroll up from that point to see the full test execution and various pod log dumps):
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/825/consoleFull#-96346004956cbb9a5e4b02b88ae8c2f77

@jimmidyson

**Comment by jimmidyson** [comment] 2016-11-24 13:31
Could we increase Jenkins log level for `io.fabric8` logger to ALL? I think this is working properly, but there was some issue connecting to the API server. The repeated stack traces[1] show that the same operation failed twice. This correlates with the test timeout (10 seconds) as we have a read timeout on websocket connections of 5 seconds, hence the two stack traces. We use background ping/pongs to reset the read timeout & hence keep long running connections alive. The reason for that is that we've hit many issues with TCP connections not timing out properly if server dies without properly closing connections.

[1]  These are bad stacktraces as using `printStackTrace` rather than log statements so no time in message unfortunately - fixing in kube client, will upgrade but doesn't affect functionality so no need for version bump of sync plugin.

**Comment by bparees** [comment] 2016-11-24 15:10
Setting logging within the test case may be tricky, i'll have to look into it later.  In the meantime, this test failed again last night, so it definitely appears semi-consistent.

I doubt it's working properly though, since the openshift build object exists and is in the new state:

```
** Build Description:
Name:		sample-pipeline-1
Namespace:	extended-test-jenkins-pipeline-rnd6o-fbfct
Created:	About an hour ago
Labels:		app=jenkins-pipeline-example
		buildconfig=sample-pipeline
		name=sample-pipeline
		openshift.io/build-config.name=sample-pipeline
		openshift.io/build.start-policy=Serial
		template=jenkins-pipeline-test
Annotations:	openshift.io/build-config.name=sample-pipeline
		openshift.io/build.number=1

Status:		New
Duration:	waiting for 1h0m2s
Build Config:	sample-pipeline
Build Pod:	sample-pipeline-1-build

Strategy:	JenkinsPipeline
Jenkinsfile contents:
  node{
  stage 'build'
  openshiftBuild(buildConfig: 'ruby-sample-build', showBuildLogs: 'true')
  }
Empty Source:	no input source provided

Build trigger cause:	Manually triggered

No events.
```

So i would have expected the sync plugin to have seen it and moved it to running.

**Comment by jimmidyson** [comment] 2016-11-24 16:05
Yes that is expected behaviour but from the logs looks like connection to API server is failing for some reason. Can I run this test locally?

**Comment by bparees** [comment] 2016-11-24 16:09
yeah it should be pretty easy, the steps the test goes through are seen here:
https://github.com/openshift/origin/blob/master/test/extended/builds/pipeline.go

basically runs a couple oc commands to instantiate a template (creates the jenkins server), create a buildconfig, and trigger the buildconfig, then waits to see the build succeed.

**Comment by jimmidyson** [comment] 2016-11-24 17:45
So it consistently fails locally (albeit without the connection failures, just silently ignores the build requests), yet on my local dev Jenkins, consisting of the exact same version of plugin, but less other plugins, it passes. Wondering if it's a conflict between plugins somehow.

**Comment by jimmidyson** [comment] 2016-11-24 21:32
So it's actually back to the lack of relisting. Looks like the new build event was received before Jenkins had created & initialised jobs properly. Added relisting in jenkinsci/openshift-sync-plugin#29.

@bparees What's the best way to test the fix out in the Jenkins image? Would like to be able to run test suite against a locally built Jenkins image if possible.

**Comment by bparees** [comment] 2016-11-24 22:39
Hack up the jenkins deployment config in the  template to deploy a docker
image reference instead of an image stream reference. Make sure the docker
image exists locally and it should just get used/deployed.

Ben Parees | OpenShift

**Comment by jimmidyson** [comment] 2016-11-24 22:40
Ah yeah perfect - thanks!

**Comment by jimmidyson** [comment] 2016-11-25 10:38
Tested successfully. Merging jenkinsci/openshift-sync-plugin#29 & will release ASAP, ready for Jenkins image bump.

**Closed by jimmidyson** 2016-11-25 10:38 UTC
